# Generated by Django 5.2.5 on 2025-09-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_django_api_admin', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
