# Generated by Django 5.2.12 on 2026-03-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django_api_admin', '0003_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
