# Generated by Django 5.2.12 on 2026-04-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_django_api_admin', '0005_category_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_django_api_admin.article')),
            ],
        ),
    ]
